/*
 * THIS FILE IS MACHINE-GENERATED. DO NOT EDIT.
 *
 * Content generated by Echelon IzoT Interface Interpreter 1.10.03 at 24-Feb-2015 13:10
 * Copyright (c) Echelon Corporation 2015
 *
 * Target: Echelon IzoT ShortStack (SS430_FT6050_SYS20000kHz)
 *
 * Use of this code is subject to your compliance with the terms of the
 * Echelon IzoT(tm) ShortStack License Agreement which is
 * available at www.echelon.com
 */
#include <string.h>
#include "regularDev.h"
#include "ShortStackApi.h"

/*
 * Message tag initialization
 */
static void tags_init(void) {
}   // tags_init

/* end Message tag initialization */

/*
 * Device datapoint initialization
 */
static void device_datapoints_init(void) {
}   // device_datapoints_init

/* end Device datapoint initialization */

/*
 * Device property initialization
 */
static void device_properties_init(void) {
}   // device_properties_init

/* end Device property initialization */

/*
 * Block initialization
 */
static SCPTminDeltaCO2 regularCO2__nvoCO2ppm__nciCO2MinDelta;
static SCPTmaxSendTime regularCO2__nciMaxSendTime;
static SCPTminSendTime regularCO2__nciMinSendTime;

static void blocks_init(void) {
   memset(&regularCO2, 0, sizeof(regularCO2));
   regularCO2.global_index = 0;
   regularCO2.nvoCO2ppm.global_index = 0;
   regularCO2.nvoCO2ppm.nciCO2MinDelta = &regularCO2__nvoCO2ppm__nciCO2MinDelta;
   regularCO2.nciMaxSendTime = &regularCO2__nciMaxSendTime;
   regularCO2.nciMinSendTime = &regularCO2__nciMinSendTime;
}   // blocks_init

/* end Block initialization */

/*
 * Datapoint table
 */
#define DVPTR(item) (void* const)&(item.data)   /* produces an NV value pointer */
#define PVPTR(item) (void* const)&item          /* produces a property value pointer */

static const LonNvDescription nvTable[] = {
   {DVPTR(regularCO2.nvoCO2ppm), 2, 0x80},
   {PVPTR(regularCO2__nvoCO2ppm__nciCO2MinDelta), 2, 0x40},
   {PVPTR(regularCO2__nciMaxSendTime), 2, 0x40},
   {PVPTR(regularCO2__nciMinSendTime), 2, 0x40},
};
/* end Datapoint table */

/*
 * Self-identification data
 */
static const LonByte siData[] =
{
   0x00, 0x7F, 0x04, 0x01, 0x00, 0x00, 0x8E, 0x1D,
   0x8F, 0x1D, 0x8F, 0x6B, 0x8F, 0x6B, 0x26, 0x33,
   0x2E, 0x34, 0x40, 0x31, 0x30, 0x37, 0x30, 0x43,
   0x4F, 0x32, 0x00, 0x30, 0x6E, 0x76, 0x6F, 0x43,
   0x4F, 0x32, 0x70, 0x70, 0x6D, 0x00, 0x40, 0x30,
   0x7C, 0x31, 0x00, 0x30, 0x6E, 0x63, 0x69, 0x43,
   0x4F, 0x32, 0x4D, 0x69, 0x6E, 0x44, 0x65, 0x6C,
   0x74, 0x61, 0x00, 0x26, 0x32, 0x2C, 0x30, 0x2C,
   0x30, 0x80, 0x2C, 0x36, 0x33, 0x00, 0x30, 0x6E,
   0x63, 0x69, 0x4D, 0x61, 0x78, 0x53, 0x65, 0x6E,
   0x64, 0x54, 0x69, 0x6D, 0x65, 0x00, 0x26, 0x31,
   0x2C, 0x30, 0x2C, 0x30, 0x80, 0x2C, 0x34, 0x39,
   0x00, 0x30, 0x6E, 0x63, 0x69, 0x4D, 0x69, 0x6E,
   0x53, 0x65, 0x6E, 0x64, 0x54, 0x69, 0x6D, 0x65,
   0x00, 0x26, 0x31, 0x2C, 0x30, 0x2C, 0x30, 0x80,
   0x2C, 0x35, 0x32, 0x00, 0xC0, 0x00, 0x7F
};

/*
 * Application initialization data
 *
 * The Micro Server uses a 16 bit signature while IzoT Interface Interpreter
 * supports a stronger 32-bit signature. The initialialization
 * data below uses a 16-bit signature derived from the 32 bit
 * version by folding the higher 16 bits into the lower 16 bits
 * with an exclusive-or combination.
 */
static const LonByte appInitData[] =
{
   /* Folded signature */
   0x9B, 0x8D,
   /* Program Id */
   0x9F, 0xFF, 0xFF, 0x0A, 0x46, 0x04, 0x04, 0x00,
   /* Communication parameters */
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   LON_USE_DEFAULT_COMMPARAMS | LON_EXPLICIT_ADDRESSING | LON_SERVICE_PIN_TIMER,
   LON_NV_COUNT,
   /* NV registration data */
   0x40, 0x00, 0x00, 0x00
};

/*
 * onUpdate event dispatcher
 */
void regularLonNvUpdateOccurred(
   const unsigned index,
   const LonReceiveAddress* const pSourceAddress
) {
}
/* end onUpdate event dispatcher */

/*
 * onComplete event dispatcher
 */
void regularLonNvUpdateCompleted(
   const unsigned index,
   const LonBool success
) {
}
/* end onComplete event dispatcher */

/*
 * IzotGetCurrentDatapointSize event handler
 */
const unsigned regularLonGetCurrentNvSize(const unsigned index) {
   unsigned result = (unsigned)nvTable[index].DeclaredSize;
   return result;
}
/* end IzotGetCurrentDatapointSize event handler */

/*
 * onOnline event dispatcher
 */
void regularLonOnline(void) {
}
/* end onOnline event dispatcher */

/*
 * onOffline event dispatcher
 */
void regularLonOffline(void) {
}
/* end onOffline event dispatcher */

/*
 * onReset event dispatcher
 */
void regularLonResetOccurred(const LonResetNotification* const pResetNotification) {
}
/* end onReset event dispatcher */

/*
 * onService event dispatcher
 */
static void onService_dispatcher(LonBool held) {
}

void regularLonServicePinPressed(void) {
   onService_dispatcher(FALSE);
}

void regularLonServicePinHeld(void) {
   onService_dispatcher(TRUE);
}

/* end onService event dispatcher */

/*
 * onWink event dispatcher
 */
void regularLonWink(void) {
}
/* end onWink event dispatcher */

const LonByte* regularLonGetSiData(unsigned* pLength) {
   *pLength = (unsigned)sizeof(siData);
   return siData;
}

const LonByte* regularLonGetAppInitData(void) {
   return appInitData;
}

void* regularLonGetNvTable(void) {
   return (void*)nvTable;
}

unsigned regularLonGetNvCount(void) {
   return LON_NV_COUNT;
}

unsigned regularLonGetMtCount(void) {
   return LON_MT_COUNT;
}

LonUbits32 regularLonGetSignature(void) {
   return (LonUbits32)LON_APP_SIGNATURE;
}

void regularLonFrameworkInit(void) {
   /* called by LonInit */
   tags_init();
   device_datapoints_init();
   device_properties_init();
   blocks_init();
}
