/*
 * THIS FILE IS MACHINE-GENERATED. DO NOT EDIT.
 *
 * Content generated by Echelon IzoT Interface Interpreter 1.10.03 at 23-Feb-2015 11:00
 * Copyright (c) Echelon Corporation 2015
 *
 * Target: Echelon IzoT ShortStack (SS430_FT6050_SYS20000kHz)
 *
 * Use of this code is subject to your compliance with the terms of the
 * Echelon IzoT(tm) ShortStack License Agreement which is
 * available at www.echelon.com
 */
#ifndef DEFINED_SHORTSTACKDEV_H
    /* Define macro derived from the current output name */
#   define DEFINED_SHORTSTACKDEV_H

#define LON_FRAMEWORK_TYPE_III 1

#include <stddef.h>
#include "LonPlatform.h"

/*
 * Data type definitions
 */
typedef LonBits8 object_request_t;
#define RQ_NUL -1    /* enum object_request_t */
#define RQ_NORMAL 0    /* enum object_request_t */
#define RQ_DISABLED 1    /* enum object_request_t */
#define RQ_UPDATE_STATUS 2    /* enum object_request_t */
#define RQ_SELF_TEST 3    /* enum object_request_t */
#define RQ_UPDATE_ALARM 4    /* enum object_request_t */
#define RQ_REPORT_MASK 5    /* enum object_request_t */
#define RQ_OVERRIDE 6    /* enum object_request_t */
#define RQ_ENABLE 7    /* enum object_request_t */
#define RQ_RMV_OVERRIDE 8    /* enum object_request_t */
#define RQ_CLEAR_STATUS 9    /* enum object_request_t */
#define RQ_CLEAR_ALARM 10    /* enum object_request_t */
#define RQ_ALARM_NOTIFY_ENABLED 11    /* enum object_request_t */
#define RQ_ALARM_NOTIFY_DISABLED 12    /* enum object_request_t */
#define RQ_MANUAL_CTRL 13    /* enum object_request_t */
#define RQ_REMOTE_CTRL 14    /* enum object_request_t */
#define RQ_PROGRAM 15    /* enum object_request_t */
#define RQ_CLEAR_RESET 16    /* enum object_request_t */
#define RQ_RESET 17    /* enum object_request_t */
#define RQ_CLEAR_LOG 18    /* enum object_request_t */
#define RQ_LOAD_PROGRAM 19    /* enum object_request_t */
#define RQ_RUN_PROGRAM 20    /* enum object_request_t */
#define RQ_HALT_PROGRAM 21    /* enum object_request_t */
#define RQ_RESTART_PROGRAM 22    /* enum object_request_t */
#define RQ_UNLOAD_PROGRAM 23    /* enum object_request_t */
#define RQ_STEP_PROGRAM 24    /* enum object_request_t */

typedef LON_STRUCT_BEGIN(SNVT_obj_request) {
    LonWord object_id;
    object_request_t object_request;
} LON_STRUCT_END(SNVT_obj_request);

/* Literals for SNVT_obj_status.flags */
#define ST_INVALID_ID        0x80000000
#define ST_INVALID_REQUEST   0x40000000
#define ST_DISABLED          0x20000000
#define ST_OUT_OF_LIMITS     0x10000000
#define ST_OPEN_CIRCUIT      0x08000000
#define ST_OUT_OF_SERVICE    0x04000000
#define ST_MECHANICAL_FAULT  0x02000000
#define ST_FEEDBACK_FAILURE  0x01000000
#define ST_OVER_RANGE        0x00800000
#define ST_UNDER_RANGE       0x00400000
#define ST_ELECTRICAL_FAULT  0x00200000
#define ST_UNABLE_TO_MEASURE 0x00100000
#define ST_COMM_FAILURE      0x00080000
#define ST_FAIL_SELF_TEST    0x00040000
#define ST_SELF_TEST_IN_PROGRESS  0x00020000
#define ST_LOCKED_OUT        0x00010000
#define ST_MANUAL_CONTROL    0x00008000
#define ST_IN_ALARM          0x00004000
#define ST_IN_OVERRIDE       0x00002000
#define ST_REPORT_MASK       0x00001000
#define ST_PROGRAMMING_MODE  0x00000800
#define ST_PROGRAMMING_FAIL  0x00000400
#define ST_ALARM_NOTIFY_DISABLED  0x00000200
#define ST_RESET_COMPLETE    0x00000100

typedef LON_STRUCT_BEGIN(SNVT_obj_status) {
    LonWord object_id;
    LonDoubleWord flags;
} LON_STRUCT_END(SNVT_obj_status);

typedef LonByte SCPTdevMajVer;

typedef LonByte SCPTdevMinVer;

typedef LON_STRUCT_BEGIN(SNVT_str_asc) {
    LonByte ascii_[31];
} LON_STRUCT_END(SNVT_str_asc);

typedef SNVT_str_asc SCPTlocation;

typedef LonBits8 config_source_t;
#define CFG_NUL -1    /* enum config_source_t */
#define CFG_LOCAL 0    /* enum config_source_t */
#define CFG_EXTERNAL 1    /* enum config_source_t */

typedef config_source_t SNVT_config_src;

typedef SNVT_config_src SCPTnwrkCnfg;

typedef LonWord SNVT_ppm;

typedef SNVT_ppm SCPTminDeltaCO2;

typedef SNVT_ppm SCPToffsetCO2;

typedef LonWord SNVT_time_sec;

typedef SNVT_time_sec SCPTmaxSendTime;

typedef SNVT_time_sec SCPTminSendTime;

/* end Data type definitions */

/*
 * Block type definitions and references
 */
#define SFPTnodeObject(mod)   SFPTnodeObject_##mod
typedef struct {
   unsigned global_index;
   struct {
      SNVT_obj_request data;
      unsigned global_index;
   } nviRequest;
   struct {
      SNVT_obj_status data;
      unsigned global_index;
   } nvoStatus;
   SCPTdevMajVer* nciDevMajVer;
   SCPTdevMinVer* nciDevMinVer;
   SCPTlocation* nciLocation;
   SCPTnwrkCnfg* nciNetConfig;
} SFPTnodeObject_node;

extern SFPTnodeObject_node nodeObject;

#define SFPTco2Sensor(mod)   SFPTco2Sensor_##mod
typedef struct {
   unsigned global_index;
   struct {
      SNVT_ppm data;
      unsigned global_index;
      SCPTminDeltaCO2* nciCO2MinDelta;
      SCPToffsetCO2* nciCO2Offset;
   } nvoCO2ppm;
   SCPTmaxSendTime* nciMaxSendTime;
   SCPTminSendTime* nciMinSendTime;
} SFPTco2Sensor_deluxe;

extern SFPTco2Sensor_deluxe deluxeCO2[4];

#define LON_FB_COUNT 5
/* end Block type definitions and references */

/*
 * Device datapoint references
 */
/* end Device datapoint references */

/*
 * Device property references
 */
/* end Device property references */

/*
 * Message tag references
 */
/* end Message tag references */

#define LON_NV_COUNT 26
/* For compatibility with older ShortStack applications */
#define LonNvCount LON_NV_COUNT
#define LON_PERSISTENT_NVS 20
#define LON_MT_COUNT 0
/* For compatibility with older ShortStack applications */
#define LonMtCount LON_MT_COUNT

#define LON_APP_OUTPUT_BUFSIZE 146
#define LON_APP_INPUT_BUFSIZE 146
#define LON_ISI_ENABLED 0x00
#define LON_EXPLICIT_ADDRESSING (LON_ISI_ENABLED)
#define LON_USE_DEFAULT_COMMPARAMS 0x40 /* see LonCustomCommunicationParameters() */
#define LON_APP_SIGNATURE 0xCBB5C05B
#define LON_APPLICATION_MESSAGES 0
#define LON_SERVICE_PIN_TIMER 0
#define LON_PROGRAM_ID "9F:FF:FF:0A:46:04:04:01"

#define LON_NM_QUERY_FUNCTIONS 0
#define LON_NM_UPDATE_FUNCTIONS 0
#define LON_UTILITY_FUNCTIONS 0

#define LON_DMF_WINDOW_ENABLED 0
#define LON_DMF_WINDOW_SIZE    0

extern const LonByte* deluxeLonGetSiData(unsigned* pLength);
extern const LonByte* deluxeLonGetAppInitData(void);
extern void* deluxeLonGetNvTable(void);
extern unsigned deluxeLonGetNvCount(void);
extern unsigned deluxeLonGetMtCount(void);
extern LonUbits32 deluxeLonGetSignature(void);
extern void deluxeLonFrameworkInit(void);

#ifndef DEFINED_SHORTSTACKDEV_H
    /* Define this unless same as output name */
#   define DEFINED_SHORTSTACKDEV_H
#endif
#endif   /* DEFINED_SHORTSTACKDEV_H */
