/*
 * THIS FILE IS MACHINE-GENERATED. DO NOT EDIT.
 *
 * Content generated by Echelon IzoT Interface Interpreter 1.10.03 at 20-Feb-2015 15:16
 * Copyright (c) Echelon Corporation 2015
 *
 * Target: Echelon IzoT ShortStack (SS430_FT6050_SYS20000kHz)
 *
 * Use of this code is subject to your compliance with the terms of the
 * Echelon IzoT(tm) ShortStack License Agreement which is
 * available at www.echelon.com
 */
#include <string.h>
#include "ShortStackDev.h"
#include "ShortStackApi.h"

/*
 * Message tag initialization
 */
static void tags_init(void) {
}   // tags_init

/* end Message tag initialization */

/*
 * Device datapoint initialization
 */
static void device_datapoints_init(void) {
}   // device_datapoints_init

/* end Device datapoint initialization */

/*
 * Device property initialization
 */
static void device_properties_init(void) {
}   // device_properties_init

/* end Device property initialization */

/*
 * Block initialization
 */
static SCPTdevMajVer nodeObject__nciDevMajVer;
static SCPTdevMinVer nodeObject__nciDevMinVer;
static SCPTlocation nodeObject__nciLocation;
static SCPTnwrkCnfg nodeObject__nciNetConfig;
static SCPTlocation driver__0__nciLocation;
static SCPTlocation driver__1__nciLocation;

static void blocks_init(void) {
   memset(&nodeObject, 0, sizeof(nodeObject));
   nodeObject.global_index = 0;
   nodeObject.nviRequest.global_index = 0;
   nodeObject.nvoStatus.global_index = 1;
   nodeObject.nciDevMajVer = &nodeObject__nciDevMajVer;
   {
      const LonByte init[] = {1};
      memcpy(&nodeObject__nciDevMajVer, init, sizeof(init));
   }
   nodeObject.nciDevMinVer = &nodeObject__nciDevMinVer;
   memset(&nodeObject__nciDevMinVer, 0, sizeof(nodeObject__nciDevMinVer));
   nodeObject.nciLocation = &nodeObject__nciLocation;
   memset(&nodeObject__nciLocation, 0, sizeof(nodeObject__nciLocation));
   nodeObject.nciNetConfig = &nodeObject__nciNetConfig;
   {
      const LonByte init[] = {1};
      memcpy(&nodeObject__nciNetConfig, init, sizeof(init));
   }
   memset(&driver, 0, sizeof(driver));
   driver[0].global_index = 1;
   driver[0].nviValue.global_index = 6;
   driver[0].nvoValueFb.global_index = 7;
   driver[0].nciLocation = &driver__0__nciLocation;
   {
      const LonByte init[] = {114, 111, 111, 109, 32, 49, 48, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
      memcpy(&driver__0__nciLocation, init, sizeof(init));
   }
   driver[1].global_index = 2;
   driver[1].nviValue.global_index = 9;
   driver[1].nvoValueFb.global_index = 10;
   driver[1].nciLocation = &driver__1__nciLocation;
   {
      const LonByte init[] = {114, 111, 111, 109, 32, 49, 48, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
      memcpy(&driver__1__nciLocation, init, sizeof(init));
   }
}   // blocks_init

/* end Block initialization */

/*
 * Datapoint table
 */
#define DVPTR(item) (void* const)&(item.data)   /* produces an NV value pointer */
#define PVPTR(item) (void* const)&item          /* produces a property value pointer */

static const LonNvDescription nvTable[] = {
   {DVPTR(nodeObject.nviRequest), 3, 0x00},
   {DVPTR(nodeObject.nvoStatus), 6, 0x80},
   {PVPTR(nodeObject__nciDevMajVer), 1, 0x40},
   {PVPTR(nodeObject__nciDevMinVer), 1, 0x40},
   {PVPTR(nodeObject__nciLocation), 31, 0x40},
   {PVPTR(nodeObject__nciNetConfig), 1, 0x40},
   {DVPTR(driver[0].nviValue), 2, 0x00},
   {DVPTR(driver[0].nvoValueFb), 2, 0x80},
   {PVPTR(driver__0__nciLocation), 31, 0x40},
   {DVPTR(driver[1].nviValue), 2, 0x00},
   {DVPTR(driver[1].nvoValueFb), 2, 0x80},
   {PVPTR(driver__1__nciLocation), 31, 0x40},
};
/* end Datapoint table */

/*
 * Self-identification data
 */
static const LonByte siData[] =
{
   0x01, 0x35, 0x0C, 0x01, 0x00, 0x00, 0x8E, 0x5C,
   0x8E, 0x5D, 0x8F, 0x00, 0x8F, 0x00, 0x8F, 0x24,
   0x8F, 0x45, 0x8E, 0x2C, 0x8E, 0x2C, 0x8F, 0x24,
   0x8E, 0x2C, 0x8E, 0x2C, 0x8F, 0x24, 0x26, 0x33,
   0x2E, 0x34, 0x40, 0x30, 0x6E, 0x6F, 0x64, 0x65,
   0x4F, 0x62, 0x6A, 0x65, 0x63, 0x74, 0x2C, 0x34,
   0x5B, 0x32, 0x76, 0x6F, 0x6C, 0x74, 0x73, 0x00,
   0x30, 0x6E, 0x76, 0x69, 0x52, 0x65, 0x71, 0x75,
   0x65, 0x73, 0x74, 0x00, 0x40, 0x30, 0x7C, 0x31,
   0x00, 0x30, 0x6E, 0x76, 0x6F, 0x53, 0x74, 0x61,
   0x74, 0x75, 0x73, 0x00, 0x40, 0x30, 0x7C, 0x32,
   0x00, 0x30, 0x6E, 0x63, 0x69, 0x44, 0x65, 0x76,
   0x4D, 0x61, 0x6A, 0x56, 0x65, 0x72, 0x00, 0x26,
   0x31, 0x2C, 0x30, 0x2C, 0x30, 0x84, 0x2C, 0x31,
   0x36, 0x35, 0x00, 0x30, 0x6E, 0x63, 0x69, 0x44,
   0x65, 0x76, 0x4D, 0x69, 0x6E, 0x56, 0x65, 0x72,
   0x00, 0x26, 0x31, 0x2C, 0x30, 0x2C, 0x30, 0xA4,
   0x2C, 0x31, 0x36, 0x36, 0x00, 0x30, 0x6E, 0x63,
   0x69, 0x4C, 0x6F, 0x63, 0x61, 0x74, 0x69, 0x6F,
   0x6E, 0x00, 0x26, 0x31, 0x2C, 0x30, 0x2C, 0x30,
   0x80, 0x2C, 0x31, 0x37, 0x00, 0x30, 0x6E, 0x63,
   0x69, 0x4E, 0x65, 0x74, 0x43, 0x6F, 0x6E, 0x66,
   0x69, 0x67, 0x00, 0x26, 0x31, 0x2C, 0x30, 0x2C,
   0x30, 0x80, 0x2C, 0x32, 0x35, 0x00, 0x30, 0x6E,
   0x76, 0x69, 0x56, 0x61, 0x6C, 0x75, 0x65, 0x00,
   0x40, 0x31, 0x7C, 0x31, 0x00, 0x30, 0x6E, 0x76,
   0x6F, 0x56, 0x61, 0x6C, 0x75, 0x65, 0x46, 0x62,
   0x00, 0x40, 0x31, 0x7C, 0x32, 0x00, 0x30, 0x6E,
   0x63, 0x69, 0x4C, 0x6F, 0x63, 0x61, 0x74, 0x69,
   0x6F, 0x6E, 0x31, 0x00, 0x26, 0x31, 0x2C, 0x31,
   0x2C, 0x30, 0x80, 0x2C, 0x31, 0x37, 0x00, 0x30,
   0x6E, 0x76, 0x69, 0x56, 0x61, 0x6C, 0x75, 0x65,
   0x31, 0x00, 0x40, 0x32, 0x7C, 0x31, 0x00, 0x30,
   0x6E, 0x76, 0x6F, 0x56, 0x61, 0x6C, 0x75, 0x65,
   0x46, 0x62, 0x31, 0x00, 0x40, 0x32, 0x7C, 0x32,
   0x00, 0x30, 0x6E, 0x63, 0x69, 0x4C, 0x6F, 0x63,
   0x61, 0x74, 0x69, 0x6F, 0x6E, 0x32, 0x00, 0x26,
   0x31, 0x2C, 0x32, 0x2C, 0x30, 0x80, 0x2C, 0x31,
   0x37, 0x00, 0xC0, 0x00, 0x7F
};

/*
 * Application initialization data
 *
 * The Micro Server uses a 16 bit signature while IzoT Interface Interpreter
 * supports a stronger 32-bit signature. The initialialization
 * data below uses a 16-bit signature derived from the 32 bit
 * version by folding the higher 16 bits into the lower 16 bits
 * with an exclusive-or combination.
 */
static const LonByte appInitData[] =
{
   /* Folded signature */
   0x55, 0x91,
   /* Program Id */
   0x9F, 0xFF, 0xFF, 0x08, 0x16, 0x01, 0x04, 0x00,
   /* Communication parameters */
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   LON_USE_DEFAULT_COMMPARAMS | LON_EXPLICIT_ADDRESSING | LON_SERVICE_PIN_TIMER,
   LON_NV_COUNT,
   /* NV registration data */
   0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x60,
   0x00, 0x00, 0x60, 0x00
};

/*
 * onUpdate event handler specifications
 */
extern void onNviRequest(const unsigned index, const LonReceiveAddress* const pSourceAddress);
extern void onDriverUpdate(const unsigned index, const LonReceiveAddress* const pSourceAddress);
/* end onUpdate event handler specifications */

/*
 * onUpdate event dispatcher
 */
void LonNvUpdateOccurred(
   const unsigned index,
   const LonReceiveAddress* const pSourceAddress
) {
   if (
       index == 0 // nodeObject.nviRequest
   ) {
      onNviRequest(index, pSourceAddress);
   }
   if (
       index == 6 // driver[0].nviValue
   ||  index == 9 // driver[1].nviValue
   ) {
      onDriverUpdate(index, pSourceAddress);
   }
}
/* end onUpdate event dispatcher */

/*
 * onComplete event dispatcher
 */
void LonNvUpdateCompleted(
   const unsigned index,
   const LonBool success
) {
}
/* end onComplete event dispatcher */

/*
 * IzotGetCurrentDatapointSize event handler
 */
const unsigned LonGetCurrentNvSize(const unsigned index) {
   unsigned result = (unsigned)nvTable[index].DeclaredSize;
   return result;
}
/* end IzotGetCurrentDatapointSize event handler */

/*
 * onOnline event dispatcher
 */
void LonOnline(void) {
}
/* end onOnline event dispatcher */

/*
 * onOffline event dispatcher
 */
void LonOffline(void) {
}
/* end onOffline event dispatcher */

/*
 * onReset event dispatcher
 */
void LonResetOccurred(const LonResetNotification* const pResetNotification) {
}
/* end onReset event dispatcher */

/*
 * onService event dispatcher
 */
static void onService_dispatcher(LonBool held) {
}

void LonServicePinPressed(void) {
   onService_dispatcher(FALSE);
}

void LonServicePinHeld(void) {
   onService_dispatcher(TRUE);
}

/* end onService event dispatcher */

/*
 * onWink event dispatcher
 */
void LonWink(void) {
}
/* end onWink event dispatcher */

const LonByte* LonGetSiData(unsigned* pLength) {
   *pLength = (unsigned)sizeof(siData);
   return siData;
}

const LonByte* LonGetAppInitData(void) {
   return appInitData;
}

void* LonGetNvTable(void) {
   return (void*)nvTable;
}

unsigned LonGetNvCount(void) {
   return LON_NV_COUNT;
}

unsigned LonGetMtCount(void) {
   return LON_MT_COUNT;
}

LonUbits32 LonGetSignature(void) {
   return (LonUbits32)LON_APP_SIGNATURE;
}

void LonFrameworkInit(void) {
   /* called by LonInit */
   tags_init();
   device_datapoints_init();
   device_properties_init();
   blocks_init();
}
