/*
 * THIS FILE IS MACHINE-GENERATED. DO NOT EDIT.
 *
 * Content generated by Echelon IzoT Interface Interpreter 1.10.06 at 27-Aug-2015 10:12
 * Copyright (c) Echelon Corporation 2015
 *
 * Target: Echelon IzoT ShortStack (SS430_FT6050ISI_SYS20000kHz)
 *
 * Use of this code is subject to your compliance with the terms of the
 * Echelon IzoT(tm) ShortStack License Agreement which is
 * available at www.echelon.com
 */
#include <string.h>
#include "ShortStackDev.h"
#include "ShortStackApi.h"

/*
 * Message tag initialization
 */
static void tags_init(void) {
}   // tags_init

/* end Message tag initialization */

/*
 * Property files
 */
static void property_files_init(void) {
}   // property_files_init

/* end Property files */

/*
 * Device datapoint initialization
 */
static void device_datapoints_init(void) {
}   // device_datapoints_init

/* end Device datapoint initialization */

/*
 * Device property initialization
 */
static void device_properties_init(void) {
}   // device_properties_init

/* end Device property initialization */

/*
 * Block initialization
 */
static SCPTdevMajVer nodeObject__nciDevMajVer;
static SCPTdevMinVer nodeObject__nciDevMinVer;
static SCPTlocation nodeObject__nciLocation;
static SCPTnwrkCnfg nodeObject__nciNetConfig;
static SCPTupdateRate rtc__nvoTimeDate__nciUpdateRate;

static void blocks_init(void) {
   memset(&nodeObject, 0, sizeof(nodeObject));
   nodeObject.global_index = 0;
   nodeObject.nviRequest.global_index = 0;
   nodeObject.nvoStatus.global_index = 1;
   nodeObject.nciDevMajVer = &nodeObject__nciDevMajVer;
   {
      const LonByte init[] = {1};
      memcpy(&nodeObject__nciDevMajVer, init, sizeof(init));
   }
   nodeObject.nciDevMinVer = &nodeObject__nciDevMinVer;
   memset(&nodeObject__nciDevMinVer, 0, sizeof(nodeObject__nciDevMinVer));
   nodeObject.nciLocation = &nodeObject__nciLocation;
   memset(&nodeObject__nciLocation, 0, sizeof(nodeObject__nciLocation));
   nodeObject.nciNetConfig = &nodeObject__nciNetConfig;
   memset(&nodeObject__nciNetConfig, 0, sizeof(nodeObject__nciNetConfig));
   memset(&rtc, 0, sizeof(rtc));
   rtc.global_index = 1;
   rtc.nvoTimeDate.global_index = 6;
   rtc.nvoTimeDate.nciUpdateRate = &rtc__nvoTimeDate__nciUpdateRate;
   {
      const LonByte init[] = {2, 88};
      memcpy(&rtc__nvoTimeDate__nciUpdateRate, init, sizeof(init));
   }
   memset(&display, 0, sizeof(display));
   display.global_index = 2;
   display.nviValue.global_index = 8;
}   // blocks_init

/* end Block initialization */

/*
 * Datapoint table
 */
#define DVPTR(item) (void* const)&(item.data)   /* produces an NV value pointer */
#define PVPTR(item) (void* const)&item          /* produces a property value pointer */

static const LonNvDescription nvTable[] = {
   {DVPTR(nodeObject.nviRequest), 3, 0x00},
   {DVPTR(nodeObject.nvoStatus), 6, 0x80},
   {PVPTR(nodeObject__nciDevMajVer), 1, 0x40},
   {PVPTR(nodeObject__nciDevMinVer), 1, 0x40},
   {PVPTR(nodeObject__nciLocation), 31, 0x40},
   {PVPTR(nodeObject__nciNetConfig), 1, 0x40},
   {DVPTR(rtc.nvoTimeDate), 7, 0x80},
   {PVPTR(rtc__nvoTimeDate__nciUpdateRate), 2, 0x40},
   {DVPTR(display.nviValue), 7, 0x00},
};
/* end Datapoint table */

/*
 * Self-identification data
 */
static const LonByte siData[] =
{
   0x01, 0x05, 0x09, 0x01, 0x00, 0x00, 0x8E, 0x5C,
   0x8E, 0x5D, 0x8F, 0x00, 0x8F, 0x00, 0x8F, 0x24,
   0x8F, 0x45, 0x8E, 0x54, 0x8F, 0x6B, 0x8E, 0x54,
   0x26, 0x33, 0x2E, 0x34, 0x40, 0x30, 0x6E, 0x6F,
   0x64, 0x65, 0x4F, 0x62, 0x6A, 0x65, 0x63, 0x74,
   0x2C, 0x33, 0x33, 0x30, 0x30, 0x63, 0x6C, 0x6F,
   0x63, 0x6B, 0x2C, 0x33, 0x63, 0x6C, 0x6F, 0x63,
   0x6B, 0x44, 0x69, 0x73, 0x70, 0x6C, 0x61, 0x79,
   0x00, 0x30, 0x6E, 0x76, 0x69, 0x52, 0x65, 0x71,
   0x75, 0x65, 0x73, 0x74, 0x00, 0x40, 0x30, 0x7C,
   0x31, 0x00, 0x30, 0x6E, 0x76, 0x6F, 0x53, 0x74,
   0x61, 0x74, 0x75, 0x73, 0x00, 0x40, 0x30, 0x7C,
   0x32, 0x00, 0x30, 0x6E, 0x63, 0x69, 0x44, 0x65,
   0x76, 0x4D, 0x61, 0x6A, 0x56, 0x65, 0x72, 0x00,
   0x26, 0x31, 0x2C, 0x30, 0x2C, 0x30, 0x84, 0x2C,
   0x31, 0x36, 0x35, 0x00, 0x30, 0x6E, 0x63, 0x69,
   0x44, 0x65, 0x76, 0x4D, 0x69, 0x6E, 0x56, 0x65,
   0x72, 0x00, 0x26, 0x31, 0x2C, 0x30, 0x2C, 0x30,
   0xA4, 0x2C, 0x31, 0x36, 0x36, 0x00, 0x30, 0x6E,
   0x63, 0x69, 0x4C, 0x6F, 0x63, 0x61, 0x74, 0x69,
   0x6F, 0x6E, 0x00, 0x26, 0x31, 0x2C, 0x30, 0x2C,
   0x30, 0x80, 0x2C, 0x31, 0x37, 0x00, 0x30, 0x6E,
   0x63, 0x69, 0x4E, 0x65, 0x74, 0x43, 0x6F, 0x6E,
   0x66, 0x69, 0x67, 0x00, 0x26, 0x31, 0x2C, 0x30,
   0x2C, 0x30, 0x88, 0x2C, 0x32, 0x35, 0x00, 0x30,
   0x6E, 0x76, 0x6F, 0x54, 0x69, 0x6D, 0x65, 0x44,
   0x61, 0x74, 0x65, 0x00, 0x40, 0x31, 0x7C, 0x31,
   0x00, 0x30, 0x6E, 0x63, 0x69, 0x55, 0x70, 0x64,
   0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x65, 0x00,
   0x26, 0x32, 0x2C, 0x36, 0x2C, 0x30, 0x80, 0x2C,
   0x39, 0x38, 0x00, 0x30, 0x6E, 0x76, 0x69, 0x56,
   0x61, 0x6C, 0x75, 0x65, 0x00, 0x40, 0x32, 0x7C,
   0x31, 0x00, 0xFF, 0x00, 0x7F
};

/*
 * Application initialization data
 *
 * The Micro Server uses a 16 bit signature while IzoT Interface Interpreter
 * supports a stronger 32-bit signature. The initialialization
 * data below uses a 16-bit signature derived from the 32 bit
 * version by folding the higher 16 bits into the lower 16 bits
 * with an exclusive-or combination.
 */
static const LonByte appInitData[] =
{
   /* Folded signature */
   0x2E, 0x75,
   /* Program Id */
   0x9F, 0xFF, 0xFF, 0x08, 0x00, 0x04, 0x04, 0x00,
   /* Communication parameters */
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   LON_USE_DEFAULT_COMMPARAMS | LON_EXPLICIT_ADDRESSING | LON_SERVICE_PIN_TIMER,
   LON_NV_COUNT,
   /* NV registration data */
   0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x50, 0x00,
   0x00
};

/*
 * onUpdate event handler specifications
 */
extern void onNetConfigUpdate(const unsigned index, const LonReceiveAddress* const pSourceAddress);
extern void onClockDisplay(const unsigned index, const LonReceiveAddress* const pSourceAddress);
extern void onNviRequest(const unsigned index, const LonReceiveAddress* const pSourceAddress);
/* end onUpdate event handler specifications */

/*
 * onUpdate event dispatcher
 */
void LonNvUpdateOccurred(
   const unsigned index,
   const LonReceiveAddress* const pSourceAddress
) {
   if (
       index == 5 // nodeObject__nciNetConfig
   ) {
      onNetConfigUpdate(index, pSourceAddress);
   }
   if (
       index == 8 // display.nviValue
   ) {
      onClockDisplay(index, pSourceAddress);
   }
   if (
       index == 0 // nodeObject.nviRequest
   ) {
      onNviRequest(index, pSourceAddress);
   }
}
/* end onUpdate event dispatcher */

/*
 * onComplete event dispatcher
 */
void LonNvUpdateCompleted(
   const unsigned index,
   const LonBool success
) {
}
/* end onComplete event dispatcher */

/*
 * IzotGetCurrentDatapointSize event handler
 */
const unsigned LonGetCurrentNvSize(const unsigned index) {
   unsigned result = (unsigned)nvTable[index].DeclaredSize;
   return result;
}
/* end IzotGetCurrentDatapointSize event handler */

/*
 * onOnline event dispatcher
 */
void LonOnline(void) {
}
/* end onOnline event dispatcher */

/*
 * onOffline event dispatcher
 */
void LonOffline(void) {
}
/* end onOffline event dispatcher */

/*
 * onReset event handler specifications
 */
extern void onReset(const LonResetNotification* const pResetNotification);
/* end onReset event handler specifications */

/*
 * onReset event dispatcher
 */
void LonResetOccurred(const LonResetNotification* const pResetNotification) {
   onReset(pResetNotification);
}
/* end onReset event dispatcher */

/*
 * onService event dispatcher
 */
static void onService_dispatcher(LonBool held) {
}

void LonServicePinPressed(void) {
   onService_dispatcher(FALSE);
}

void LonServicePinHeld(void) {
   onService_dispatcher(TRUE);
}

/* end onService event dispatcher */

/*
 * onWink event handler specifications
 */
extern void onWink(void);
/* end onWink event handler specifications */

/*
 * onWink event dispatcher
 */
void LonWink(void) {
   onWink();
}
/* end onWink event dispatcher */

const LonByte* LonGetSiData(unsigned* pLength) {
   *pLength = (unsigned)sizeof(siData);
   return siData;
}

const LonByte* LonGetAppInitData(void) {
   return appInitData;
}

void* LonGetNvTable(void) {
   return (void*)nvTable;
}

unsigned LonGetNvCount(void) {
   return LON_NV_COUNT;
}

unsigned LonGetMtCount(void) {
   return LON_MT_COUNT;
}

LonUbits32 LonGetSignature(void) {
   return (LonUbits32)LON_APP_SIGNATURE;
}

void LonFrameworkInit(void) {
   /* called by LonInit */
   tags_init();
   device_datapoints_init();
   device_properties_init();
   property_files_init();
   blocks_init();
}

void* LonGetFile(int fileIndex, unsigned* pSize) {
    void* result = NULL;
    return result;
}

